[build]
  publish = "dist"
  command = "yarn build"

# SPA redirects - catch all routes and serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force redirects to take precedence
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
